name: Playwright Tests

# Запускаємо workflow на будь-який пуш або pull request
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        # Вказуємо робочу папку з твоїми тестами
        working-directory: QA_Automation/src/lesson19

    steps:
      # Клонування репозиторію
      - uses: actions/checkout@v3

      # Встановлення Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Встановлення залежностей
      - name: Install dependencies
        run: npm install

      # Запуск Playwright тестів
      - name: Run Playwright tests
        run: npx playwright test
